services:
    jenkins-docker:
        image: docker:dind
        container_name: jenkins-docker
        privileged: true
        environment:
            - DOCKER_TLS_CERTDIR=
        command: --storage-driver=overlay2
        volumes:
            - jenkins-data:/var/jenkins_home
        networks:
            - jenkins

    my-jenkins:
        image: my-jenkins
        container_name: my-jenkins
        restart: on-failure
        environment:
            - DOCKER_HOST=tcp://jenkins-docker:2375
        volumes:
            - jenkins-data:/var/jenkins_home
        ports:
            - '9000:8080'
            - '50000:50000'
        networks:
            - jenkins

networks:
    jenkins:
        driver: bridge

volumes:
    jenkins-data:
