name: CI

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    checks: write
    contents: read

jobs:
    unit-tests-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up GO
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'
                  cache-dependency-path: bugtracker-backend/go.sum

            - name: Install go-junit-reports
              run: go install github.com/jstemmer/go-junit-report/v2@latest

            - name: Execute Backend Unit Tests
              working-directory: ./bugtracker-backend
              run: |
                  go test -v ./... 2>&1 | go-junit-report > test-results.xml

            - name: Publish Backend Test Result
              uses: dorny/test-reporter@v1
              if: always()
              with:
                  name: Backend Unit Test Report
                  path: bugtracker-backend/test-results.xml
                  reporter: jest-junit

    unit-tests-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'
                  cache-dependency-path: bugtracker-frontend/package-lock.json

            - name: Execute Frontend Unit Tests
              working-directory: ./bugtracker-frontend
              run: |
                  npm ci
                  npm test

            - name: Publish Frontend Test Results
              uses: dorny/test-reporter@v1
              if: always()
              with:
                  name: Frontend Unit Test Report
                  path: bugtracker-frontend/test-results.xml
                  reporter: jest-junit

    integration-tests:
        needs: [unit-tests-backend, unit-tests-frontend]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Launch Application
              run: docker compose up --build -d

            - name: Run API Tests
              working-directory: ./tests-api
              run: |
                  npm ci
                  npx wait-port localhost:8080
                  npx playwright test

            - name: Publish API Test Results
              uses: dorny/test-reporter@v1
              if: always()
              with:
                  name: API Test Report
                  path: tests-api/test-results/results.xml
                  reporter: jest-junit

            - name: Run E2E Tests
              working-directory: ./tests-e2e
              run: |
                  npm ci
                  npx playwright install --with-deps chromium
                  npx wait-port localhost:3000
                  npx playwright test

            - name: Publish E2E Test Results
              uses: dorny/test-reporter@v1
              if: always()
              with:
                  name: E2E Test Report
                  path: tests-e2e/test-results/results.xml
                  reporter: jest-junit

            - name: Run Performance Tests
              working-directory: ./tests-perf
              run: |
                  docker run --rm --network host -v $(pwd):/io -w /io grafana/k6 run script.js

            - name: Upload Playwright Reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-reports
                  path: |
                      tests-api/playwright-report/
                      tests-e2e/playwright-report/
                  retention-days: 30

            - name: Upload Performance Report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: performance-report
                  path: tests-perf/perf-results.html
                  retention-days: 30

            - name: Shutdown Application
              if: always()
              run: docker compose down

    deploy-staging:
        needs: [integration-tests]

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Flyctl
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy Backend
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              working-directory: ./bugtracker-backend
              run: flyctl deploy -c fly.staging.toml --remote-only

            - name: Deploy Frontend
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              working-directory: ./bugtracker-frontend
              run: flyctl deploy -c fly.staging.toml --remote-only

    post-e2e-tests:
        needs: [deploy-staging]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Run E2E Tests On Staging
              env:
                  PLAYWRIGHT_TEST_BASE_URL: https://bugtracker-staging-shifatbinreza.fly.dev
              working-directory: ./tests-e2e
              run: |
                  npm ci
                  npx playwright install --with-deps chromium
                  npx playwright test

            - name: Publish E2E Test Results
              uses: dorny/test-reporter@v1
              if: always()
              with:
                  name: E2E Test Report
                  path: tests-e2e/test-results/results.xml
                  reporter: jest-junit

            - name: Upload Playwright Reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-reports
                  path: |
                      tests-e2e/playwright-report/
                  retention-days: 30

    deploy-production:
        needs: [post-e2e-tests]

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Flyctl
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy Backend
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              working-directory: ./bugtracker-backend
              run: flyctl deploy -c fly.toml --remote-only

            - name: Deploy Frontend
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              working-directory: ./bugtracker-frontend
              run: flyctl deploy -c fly.toml --remote-only
